### ISSUE TITLE
ArgumentException: System.NullReferenceException

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Replicator#14]
I'v'e updated to the latest replicator bits, commit c35d06b4d85844b5cd11d7551ca1aa041cddbe10.

Running the same sample as described in OP of #12. When starting the first child, it crash with the following:

```
System.ArgumentException: The close status description 'System.NullReferenceException: Object reference not set to an instance of an object.
   at Replicator.Replicator.ProcessIncomingTransaction(LogReadResult tran) in C:\Users\Per\Git\Starcounter\Replicator\Replicator.cs:line 353
   at Replicator.Replicator.ProcessStringMessage(String message) in C:\Users\Per\Git\Starcounter\Replicator\Replicator.cs:line 375' is too long. The UTF8-representation of the status description must not be longer than 123 bytes.
Parameter name: statusDescription
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 132
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 86
ParamName=statusDescription
HResult=-2147024809
```

As in #12, this is what gets logged, and prevents me from see the real cause of the error. I'll try setting up a debug session to see if I can better diagnose what goes wrong.

**Comment by per-samuelsson** [comment]
When debugging this, it looks like the error is not originating from the replicator itself, but rather from a commit hook in the launcher, executing this method `RefreshSignInState`.

The reason the replicator report it is because it catches those exceptions and send some QUIT using the exception as a message, and the content is too long for that API, so then that exception hides the underlying problem.

I'll try more to figure out what goes wrong in the commit hook, but we must also fix the problem with the replicator. Doing `Exception.ToString()` is often returning really much data, and it looks like the close status description is limited to 123 bytes.

**Comment by per-samuelsson** [comment]
Closing this, since I broke it down into two separate issues, representing the problems I stated above: #15 and #16.
