### ISSUE TITLE
LogPositions need to be comparable

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Replicator#19]
Two databases are replicating, `repl1` and `repl2` using two LogReaders (each). During the first session, one of the LogReaderResults from `repl1` have the continuation position 286. During the second session, the transaction is read again (although with continuation position 290) causing it to be sent again, causing a `Starcounter.ConstraintViolationException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.` exception when the receiver tries to insert a record with an object ID that is already present.

When you read this, remember that a `LogPosition` is the *continuation position*, not a *commit ID*, meaning it's some position in the log beyond the transaction data being returned.

This is the transaction log of `repl1`:
```
{"continuation_position":{"commit_id":256},"transaction_data":{"creates":[{"columns":[{"name":"DatabaseGuid","value":"a7217ca9-0da3-45b1-a67e-9d63d0d17f39"},{"name":"ParentUri","value":"ANTEATER:8081"},{"name":"ParentGuid","value":""},{"name":"ReconnectMinimumWaitSeconds","value":1},{"name":"ReconnectMaximumWaitSeconds","value":86400}],"key":{"object_id":10000000},"table":"Replicator.Configuration"}],"deletes":[],"updates":[]}}
{"continuation_position":{"commit_id":257},"transaction_data":{"creates":[],"deletes":[],"updates":[{"columns":[{"name":"ParentUri","value":"ANTEATER:8082"},{"name":"ParentGuid","value":""}],"key":{"object_id":10000000},"table":"Replicator.Configuration"}]}}
{"continuation_position":{"commit_id":258},"transaction_data":{"creates":[{"columns":[{"name":"Invoice","value":{"__type":"reference:#Starcounter.TransactionLog","object_id":10000001}},{"name":"Description","value":"ett1"},{"name":"Quantity","value":1},{"name":"Price","value":0.000000}],"key":{"object_id":10000002},"table":"InvoiceRow"},{"columns":[{"name":"InvoiceNo","value":1},{"name":"Name","value":"one1"}],"key":{"object_id":10000001},"table":"Invoice"}],"deletes":[],"updates":[]}}
{"continuation_position":{"commit_id":259},"transaction_data":{"creates":[{"columns":[{"name":"Invoice","value":{"__type":"reference:#Starcounter.TransactionLog","object_id":10000001}},{"name":"Description","value":"ett2"},{"name":"Quantity","value":1}],"key":{"object_id":20000002},"table":"InvoiceRow"},{"columns":[{"name":"TableId","value":"e300b3db-a3ed-4f3f-9256-5b1a45fe7beb:"},{"name":"CommitId","value":256}],"key":{"object_id":10000003},"table":"Replicator.Replication"}],"deletes":[],"updates":[]}}
{"continuation_position":{"commit_id":260},"transaction_data":{"creates":[{"columns":[{"name":"Invoice","value":{"__type":"reference:#Starcounter.TransactionLog","object_id":20000003}},{"name":"Description","value":"två2"},{"name":"Quantity","value":1}],"key":{"object_id":20000004},"table":"InvoiceRow"},{"columns":[{"name":"InvoiceNo","value":2},{"name":"Name","value":"two2"}],"key":{"object_id":20000003},"table":"Invoice"}],"deletes":[],"updates":[{"columns":[{"name":"TableId","value":"e300b3db-a3ed-4f3f-9256-5b1a45fe7beb:"},{"name":"CommitId","value":257}],"key":{"object_id":10000003},"table":"Replicator.Replication"}]}}
{"continuation_position":{"commit_id":265},"transaction_data":{"creates":[{"columns":[{"name":"Invoice","value":{"__type":"reference:#Starcounter.TransactionLog","object_id":20000003}},{"name":"Description","value":"två1"},{"name":"Quantity","value":1}],"key":{"object_id":10000006},"table":"InvoiceRow"}],"deletes":[],"updates":[]}}
{"continuation_position":{"commit_id":266},"transaction_data":{"creates":[{"columns":[{"name":"Invoice","value":{"__type":"reference:#Starcounter.TransactionLog","object_id":10000007}},{"name":"Description","value":"tre1"},{"name":"Quantity","value":1}],"key":{"object_id":10000008},"table":"InvoiceRow"},{"columns":[{"name":"InvoiceNo","value":3},{"name":"Name","value":"three1"}],"key":{"object_id":10000007},"table":"Invoice"}],"deletes":[],"updates":[]}}
{"continuation_position":{"commit_id":267},"transaction_data":{"creates":[{"columns":[{"name":"Invoice","value":{"__type":"reference:#Starcounter.TransactionLog","object_id":20000003}},{"name":"Description","value":"två2"},{"name":"Quantity","value":1}],"key":{"object_id":20000008},"table":"InvoiceRow"},{"columns":[{"name":"TableId","value":"e300b3db-a3ed-4f3f-9256-5b1a45fe7beb:InvoiceRow"},{"name":"CommitId","value":264}],"key":{"object_id":10000009},"table":"Replicator.Replication"}],"deletes":[],"updates":[]}}
{"continuation_position":{"commit_id":272},"transaction_data":{"creates":[{"columns":[{"name":"Invoice","value":{"__type":"reference:#Starcounter.TransactionLog","object_id":20000009}},{"name":"Description","value":"tre2"},{"name":"Quantity","value":1}],"key":{"object_id":20000010},"table":"InvoiceRow"}],"deletes":[],"updates":[{"columns":[{"name":"TableId","value":"e300b3db-a3ed-4f3f-9256-5b1a45fe7beb:InvoiceRow"},{"name":"CommitId","value":265}],"key":{"object_id":10000009},"table":"Replicator.Replication"}]}}
{"continuation_position":{"commit_id":273},"transaction_data":{"creates":[{"columns":[{"name":"InvoiceNo","value":3},{"name":"Name","value":"three2"}],"key":{"object_id":20000009},"table":"Invoice"},{"columns":[{"name":"TableId","value":"e300b3db-a3ed-4f3f-9256-5b1a45fe7beb:Invoice"},{"name":"CommitId","value":269}],"key":{"object_id":10000010},"table":"Replicator.Replication"}],"deletes":[],"updates":[]}}
{"continuation_position":{"commit_id":274},"transaction_data":{"creates":[{"columns":[{"name":"InvoiceNo","value":4},{"name":"Name","value":"four2"}],"key":{"object_id":20000018},"table":"Invoice"}],"deletes":[],"updates":[{"columns":[{"name":"TableId","value":"e300b3db-a3ed-4f3f-9256-5b1a45fe7beb:Invoice"},{"name":"CommitId","value":271}],"key":{"object_id":10000010},"table":"Replicator.Replication"}]}}
{"continuation_position":{"commit_id":275},"transaction_data":{"creates":[{"columns":[{"name":"Invoice","value":{"__type":"reference:#Starcounter.TransactionLog","object_id":10000011}},{"name":"Description","value":"fyra1"},{"name":"Quantity","value":1}],"key":{"object_id":10000012},"table":"InvoiceRow"},{"columns":[{"name":"InvoiceNo","value":5},{"name":"Name","value":"four1"}],"key":{"object_id":10000011},"table":"Invoice"}],"deletes":[],"updates":[]}}
{"continuation_position":{"commit_id":276},"transaction_data":{"creates":[{"columns":[{"name":"Invoice","value":{"__type":"reference:#Starcounter.TransactionLog","object_id":10000013}},{"name":"Description","value":"sex1"},{"name":"Quantity","value":1}],"key":{"object_id":10000014},"table":"InvoiceRow"},{"columns":[{"name":"InvoiceNo","value":6},{"name":"Name","value":"six1"}],"key":{"object_id":10000013},"table":"Invoice"}],"deletes":[],"updates":[]}}
{"continuation_position":{"commit_id":281},"transaction_data":{"creates":[{"columns":[{"name":"InvoiceNo","value":6},{"name":"Name","value":"six2"}],"key":{"object_id":20000020},"table":"Invoice"}],"deletes":[],"updates":[{"columns":[{"name":"TableId","value":"e300b3db-a3ed-4f3f-9256-5b1a45fe7beb:Invoice"},{"name":"CommitId","value":273}],"key":{"object_id":10000010},"table":"Replicator.Replication"}]}}
{"continuation_position":{"commit_id":282},"transaction_data":{"creates":[{"columns":[{"name":"Invoice","value":{"__type":"reference:#Starcounter.TransactionLog","object_id":20000018}},{"name":"Description","value":"fyra2"},{"name":"Quantity","value":1}],"key":{"object_id":20000019},"table":"InvoiceRow"}],"deletes":[],"updates":[{"columns":[{"name":"TableId","value":"e300b3db-a3ed-4f3f-9256-5b1a45fe7beb:InvoiceRow"},{"name":"CommitId","value":271}],"key":{"object_id":10000009},"table":"Replicator.Replication"}]}}
{"continuation_position":{"commit_id":283},"transaction_data":{"creates":[{"columns":[{"name":"Invoice","value":{"__type":"reference:#Starcounter.TransactionLog","object_id":20000020}},{"name":"Description","value":"sex2"},{"name":"Quantity","value":1}],"key":{"object_id":20000021},"table":"InvoiceRow"}],"deletes":[],"updates":[{"columns":[{"name":"TableId","value":"e300b3db-a3ed-4f3f-9256-5b1a45fe7beb:InvoiceRow"},{"name":"CommitId","value":273}],"key":{"object_id":10000009},"table":"Replicator.Replication"}]}}
{"continuation_position":{"commit_id":284},"transaction_data":{"creates":[{"columns":[{"name":"Invoice","value":{"__type":"reference:#Starcounter.TransactionLog","object_id":20000032}},{"name":"Description","value":"sju2"},{"name":"Quantity","value":1}],"key":{"object_id":20000033},"table":"InvoiceRow"}],"deletes":[],"updates":[{"columns":[{"name":"TableId","value":"e300b3db-a3ed-4f3f-9256-5b1a45fe7beb:InvoiceRow"},{"name":"CommitId","value":281}],"key":{"object_id":10000009},"table":"Replicator.Replication"}]}}
{"continuation_position":{"commit_id":285},"transaction_data":{"creates":[{"columns":[{"name":"InvoiceNo","value":7},{"name":"Name","value":"seven2"}],"key":{"object_id":20000032},"table":"Invoice"}],"deletes":[],"updates":[{"columns":[{"name":"TableId","value":"e300b3db-a3ed-4f3f-9256-5b1a45fe7beb:Invoice"},{"name":"CommitId","value":281}],"key":{"object_id":10000010},"table":"Replicator.Replication"}]}}
{"continuation_position":{"commit_id":290},"transaction_data":{"creates":[{"columns":[{"name":"Invoice","value":{"__type":"reference:#Starcounter.TransactionLog","object_id":10000021}},{"name":"Description","value":"åtta1"},{"name":"Quantity","value":1}],"key":{"object_id":10000022},"table":"InvoiceRow"},{"columns":[{"name":"InvoiceNo","value":8},{"name":"Name","value":"eight1"}],"key":{"object_id":10000021},"table":"Invoice"}],"deletes":[],"updates":[]}}
```

This is the WebSocket log for the first session. Note that transaction `286` is not present in the actual log (above), since it's a continuation position, not a commit ID. It's being referenced in two lines since there is two LogReaders: one looking for `Invoice` operations, the other looking for `InvoiceRow` operations.
```
> !GUID a7217ca9-0da3-45b1-a67e-9d63d0d17f39
< !TPOS "" u261 "Invoice" u276 "InvoiceRow" u266 
> RPu275  TI"InvoiceRow" r10000012 C"Invoice" r10000011  C"Description" "fyra1"  C"Quantity" l1     
> RPu276  TI"InvoiceRow" r10000014 C"Invoice" r10000013  C"Description" "sex1"  C"Quantity" l1     
> RPu286  TI"InvoiceRow" r10000022 C"Invoice" r10000021  C"Description" "åtta1"  C"Quantity" l1     
> RPu286  TI"Invoice" r10000021 C"InvoiceNo" l8  C"Name" "eight1"     
```

This the WebSocket log for sent messages in the second session, also from `repl1`.
```
> !GUID a7217ca9-0da3-45b1-a67e-9d63d0d17f39
< !TPOS "" u261 "Invoice" u286 "InvoiceRow" u286 
> RPu290  TI"InvoiceRow" r10000022 C"Invoice" r10000021  C"Description" "åtta1"  C"Quantity" l1   I"Invoice" r10000021 C"InvoiceNo" l8  C"Name" "eight1"     
```

The second log terminates with the exception: 
```
!QUIT Starcounter.ConstraintViolationException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.
Version: 2.3.605.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001.
   at Starcounter.Internal.DbState.InsertWithId(UInt16 tableId, UInt64 oid, UInt64& address) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter\Internal\DbState.cs:line 215
   at Starcounter.TransactionLog.LogApplicator.Apply(TransactionData transaction_data) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Server\Starcounter.TransactionLog\LogApplicator.cs:line 25
   at Replicator.Replicator.<>c__DisplayClass70_0.<ProcessIncomingTransaction>b__0() in C:\Proj\Replicator\Replicator.cs:line 410
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter\Db.cs:line 259
   at Replicator.Replicator.ProcessIncomingTransaction(LogReadResult tran) in C:\Proj\Replicator\Replicator.cs:line 446
   at Replicator.Replicator.ProcessStringMessage(String message) in C:\Proj\Replicator\Replicator.cs:line 468
```

**Comment by linkdata** [comment]
After thinking, I believe this is due to the Replicator comparing the `LogPosition` continuation values. This isn't possible, since a single transaction may have different continuation positions depending on the log state when reading.

Unfortunately, I have to ensure that the Replicator doesn't commit the same transaction data twice, and the LogPosition is the only thing currently available. I've spoken with @bigwad and he will think on the best way to solve this.

The obvious solution is to use commit ID's instead of continuation positions, but there is probably a good reason why we didn't, so it may be that the Replicator will require the LogReader to be able to report both commit ID and continuation position for a transaction.

**Comment by bigwad** [comment]
Now logreader skips transactions without user data. I can change it so logreader will return empty transactiondata instead of skipping, thus providing continuation position continuity. @linkdata, is replicator able to process empty transactiondata?

**Comment by linkdata** [comment]
Yes. A transaction ending up empty for any reason (filtering etc) is not transmitted.

**Comment by linkdata** [comment]
I still need them to be stable in order to compare them. So that a given transaction only ever returns the same continuation position.

**Comment by bigwad** [comment]
>So that a given transaction only ever returns the same continuation position.

They will, due to continuity.

>A transaction ending up empty for any reason (filtering etc) is not transmitted.

There might be a reason to still transmit it to update position in receivers database. Otherwise it may ends with sender refiltering all transaction log on each receiver's connection.

**Comment by linkdata** [comment]
> There might be a reason to still transmit it to update position in receivers database. Otherwise it may ends with sender refiltering all transaction log on each receiver's connection.
I did have a check for that in an earlier version. It allowed sending an empty transaction if enough time had passed. I may add it again if needed, or more likely allow it to send an empty if X empty ones have been skipped.

**Comment by bigwad** [comment]
Pushed. Please close the issue if it helps.

**Comment by linkdata** [comment]
With that change, I'm no longer able to reproduce the error, so closing.
